/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117701-g2d81eaa37b-20241103"
#endif /* AVUTIL_FFVERSION_H */
